#!/bin/bash

rename() { echo $1 | sed 's-./--' | sed 's=sqrtPhi/=sqrtPhi--=' | sed 's=heptagon/=heptagon--=' | sed 's=/=-=' | cut -f 1 -d . ; }
move() { target=$( rename $1 ).txt; echo $target; cp $1 ~/veftxt/$target; }

# remove the rest of this file, then run:
#   find . -name '*.vef' | sed 's/^/move /' >> moves.sh

move ./rootTwo/connector.vef
move ./rootTwo/blue.vef
move ./rootTwo/yellow.vef
move ./rootTwo/brown.vef
move ./rootTwo/green.vef
move ./lifelike/connector.vef
move ./lifelike/blue.vef
move ./lifelike/yellow.vef
move ./lifelike/red.vef
move ./lifelike/yellow-short.vef
move ./lifelike/red-short.vef
move ./lifelike/green.vef
move ./heptagon/antiprism/connector.vef
move ./heptagon/antiprism/blue.vef
move ./heptagon/antiprism/red.vef
move ./octahedralRealistic/connector.vef
move ./octahedralRealistic/maroon.vef
move ./octahedralRealistic/blue.vef
move ./octahedralRealistic/yellow.vef
move ./octahedralRealistic/purple.vef
move ./octahedralRealistic/red.vef
move ./octahedralRealistic/brown.vef
move ./octahedralRealistic/green.vef
move ./octahedralRealistic/olive.vef
move ./octahedralRealistic/lavender.vef
move ./octahedralFast/connector.vef
move ./octahedralFast/blue.vef
move ./octahedralFast/yellow.vef
move ./octahedralFast/green.vef
move ./octahedral/connector.vef
move ./octahedral/maroon.vef
move ./octahedral/blue.vef
move ./octahedral/yellow.vef
move ./octahedral/purple.vef
move ./octahedral/red.vef
move ./octahedral/brown.vef
move ./octahedral/green.vef
move ./octahedral/olive.vef
move ./octahedral/lavender.vef
move ./rootTwoBig/connector.vef
move ./rootTwoBig/yellow.vef
move ./dodecs/connector.vef
move ./bigzome/connector.vef
move ./bigzome/blue.vef
move ./default/connector.vef
move ./default/snubDiagonal.vef
move ./default/black.vef
move ./default/maroon.vef
move ./default/blue.vef
move ./default/snubPentagon.vef
move ./default/yellow.vef
move ./default/spruce.vef
move ./default/rose.vef
move ./default/purple.vef
move ./default/red.vef
move ./default/brown.vef
move ./default/sand.vef
move ./default/coral.vef
move ./default/navy.vef
move ./default/snubTriangle.vef
move ./default/sulfur.vef
move ./default/cinnamon.vef
move ./default/turquoise.vef
move ./default/green.vef
move ./default/olive.vef
move ./default/apple.vef
move ./default/lavender.vef
move ./default/orange.vef
move ./default/yellow-short.vef
move ./default/red-short.vef
move ./vienne2/connector.vef
move ./vienne2/purple.vef
move ./vienne2/orange.vef
move ./vienne3/connector.vef
move ./dodecagon3d/connector.vef
move ./dodecagon3d/blue.vef
move ./dodecagon3d/green.vef
move ./tiny/black.vef
move ./tiny/maroon.vef
move ./tiny/blue.vef
move ./tiny/yellow.vef
move ./tiny/spruce.vef
move ./tiny/rose.vef
move ./tiny/purple.vef
move ./tiny/red.vef
move ./tiny/brown.vef
move ./tiny/sand.vef
move ./tiny/coral.vef
move ./tiny/navy.vef
move ./tiny/sulfur.vef
move ./tiny/cinnamon.vef
move ./tiny/turquoise.vef
move ./tiny/green.vef
move ./tiny/olive.vef
move ./tiny/apple.vef
move ./tiny/lavender.vef
move ./tiny/orange.vef
move ./sqrtPhi/fivefold/connector.vef
move ./sqrtPhi/fivefold/blue.vef
move ./sqrtPhi/fivefold/red.vef
move ./sqrtPhi/fivefold/green.vef
move ./sqrtPhi/zome/connector.vef
move ./sqrtPhi/zome/blue.vef
move ./sqrtPhi/zome/yellow.vef
move ./sqrtPhi/zome/red.vef
move ./sqrtPhi/zome/green.vef
move ./sqrtPhi/tinyIcosahedra/connector.vef
move ./sqrtPhi/tinyIcosahedra/blue.vef
move ./sqrtPhi/tinyIcosahedra/yellow.vef
move ./sqrtPhi/tinyIcosahedra/red.vef
move ./sqrtPhi/tinyIcosahedra/green.vef
move ./sqrtPhi/octahedra/ivory.vef
move ./sqrtPhi/octahedra/blue.vef
move ./sqrtPhi/octahedra/yellow.vef
move ./sqrtPhi/octahedra/mauve.vef
move ./sqrtPhi/octahedra/green.vef
move ./sqrtPhi/octahedra/slate.vef
move ./rootTwoSmall/connector.vef
move ./rootTwoSmall/blue.vef
move ./rootTwoSmall/yellow.vef
move ./rootTwoSmall/brown.vef
move ./rootTwoSmall/green.vef
move ./rootThreeOctaSmall/connector.vef
move ./rootThreeOctaSmall/blue.vef
move ./rootThreeOctaSmall/yellow.vef
move ./rootThreeOctaSmall/red.vef
move ./rootThreeOctaSmall/green.vef
